### PR TITLE
Implement new template helpers

### PR DESCRIPTION
**Pull request by strzibny**
@voxik Any ideas/complains about helpers naming?

### CODE REVIEW

**Comment by voxik** [comment]
I was thinking about something more granular, start with smaller steps. E.g. the first approximation could be to replace

```
<% for req in d.requirement -%>
# BuildRequires: rubygem(<%= d.name %>) <%= req %>
<% end -%>
```

with something like:

```
<% for req in d.requirement -%>
# BuildRequires: <%= rubygem(d) %>
<% end -%>
```

Next step could be:

```
<% for req in d.requirement -%>
# <%= build_requires(d) %>
<% end -%>
```

This would give us more flexibility and transparency. If you go with ```gem_build_requires``` as you propose, it immediately hides a lot of stuff, including that the BR is actually commented out, that we omit some gems, etc.

**Comment by strzibny** [comment]
Hmm, on one hand that is all true. On the other I don't think that changing `# BuildRequires: rubygem(<%= d.name %>) <%= req %>` to `# <%= build_requires(d) %>` helps us much (that means in this case we can just keep it the way it is). Because first, you would need to pass both `name` of gem and `req` version and at the same time we should distinguish between gem dependency and other dependencies... The idea of this is that template helpers can be more clever and be more assuming since they don't have to be used in the first place and they can be modified by `config` options in future (so the `rubygem-` prefix, list of gems to ignore, commenting out build requires should all be configuration). Just like our first two template helpers for listing files. So I would say we can have more granular helpers (and this ones could just internally use them), but I don't see a problem of having ones that do more.  I would rather ensure the clarity by documenting well both approaches.

**Comment by voxik** [comment]
I think that we agree on the end result, we are just not aligned (yet) on the approach :)

I just suggest to start with simple small helpers which replace small bits of template and later combine them (internally) into something bigger. Your PR is implemented in the opposite way, i.e. you provide helpers replacing quite a but they are internally almost duplicates.

**Comment by voxik** [comment]
As a start I implemented requirement helper 5fc0b2186

**Pull request closed without merging**
