### PR TITLE
template for centos-6

### PR DESCRIPTION
**Pull request by mighq**
* spec file template for creating packages for centos-6.
* based on fedora with small tuning

### CODE REVIEW

**Comment by junaruga** [comment]
@voxik , you mentioned me that you do not manage the template file for "Ubuntu Linux" in gem2rpm.
The reason why this pull-request is not accepted, is because you do not want to ship the template for "CentOS" in gem2rpm?

Right now Fedora, OpenSUSE, PLD Linux's templates are managed in templates directory.
https://github.com/fedora-ruby/gem2rpm/tree/v0.11.3/templates

I can suggest that we can write which OS 's template file are managed in gem2rpm, to README document, or other documents, if it does not exist such kind of document.

**Comment by voxik** [comment]
Well, there are 2 thing:

1. I don't think this template is up-to-date with current packaging policies, since the %{gem_instdir} and %{gem_dir} are supported on RHEL6 may be for over two years now?

2. The maintenance is problem. To make this useful, it has to be maintained. Is somebody willing to spend the time to maintain it?

And Ubuntu (although this is OT for this issue, but since you mention it) is totally different case. Ubuntu is not RPM based distribution, so there is no point to maintain Ubuntu template. If somebody wants to use gem2rpm on Ubuntu (s)he should use appropriate template for RPM based distribution.

**Comment by junaruga** [comment]
@voxik Thank you for the message. I understood it.

For example, if someone will send you the pull-request with latest gem2rpm specification's template for CentOS, you are going to accept it?

**Comment by voxik** [comment]
I'd love to see some commitment to maintenance, probably someone who maintains some set of packages somewhere, either in EPEL or in Copr. That would be convincing.

**Comment by junaruga** [comment]
@voxik I could understood your idea.
It seems that you have one policy for the template managed in gem2rpm. 

Its policy may be "If the template sent by pull-request, is the one for the RPM based distribution, and the person is such kind of the one who maintains some set of packages somewhere, either in EPEL or in Copr. That would be convincing, and its template has a possibility to be accepted. But otherwise not.".

I think now it is time to close this pull-request, isn't it?

**Comment by voxik** [comment]
@mighq Thx for you PR, but based on the discussion above, I'm going to close this PR now. My apologies.

**Pull request closed without merging**
