### PR TITLE
Add Ruby 3.2 to the CI, remove Ruby 2.2

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by voxik** [comment]
> Bundler started segfaulting in github actions

I assume you are referring to [this](https://github.com/fedora-ruby/gem2rpm/actions/runs/5320122162) run. Interesting 🤔 You are right that it is probably not worth of investigating.

**Comment by voxik** [comment]
Shouldn't we take this opportunity to drop the 2.1..2.4 (the 2.0 is still used in RHEL7) and probably also 2.6, 2.7, which all are EOL?

**Comment by dcermak** [comment]
> Shouldn't we take this opportunity to drop the 2.1..2.4 (the 2.0 is still used in RHEL7) and probably also 2.6, 2.7, which all are EOL?

No objection from my side. I just wanted to make the least invasive change.

**Comment by voxik** [comment]
Better to have this. Thx a lot and the PR removing all older versions as proposed above is still welcome ;)

**Pull request merged**
