### PR TITLE
handle clases when os-release file values are in quotes

### PR DESCRIPTION
**Pull request by glensc**
for example:

```
$ cat /etc/os-release 
NAME="PLD Linux"
VERSION="3.0 (Th)"
ID="pld"
VERSION_ID="3.0"
PRETTY_NAME="PLD Linux 3.0 (Th)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:pld-linux:pld:3.0"
HOME_URL="http://www.pld-linux.org/"
BUG_REPORT_URL="http://bugs.pld-linux.org/"
```

### CODE REVIEW

**Comment by voxik** [comment]
Thanks for PR. Would you mind to include some simple test case to cover this case? Probably this [1] test case could be updated with additional quoted version of os-release [2].

[1] https://github.com/fedora-ruby/gem2rpm/blob/master/test/test_distro.rb#L50
[2] https://github.com/fedora-ruby/gem2rpm/blob/master/test/templates/fake_files/os-release

**Comment by glensc** [comment]
how to run tests? can't find any docs (in your project) and i'm not ruby guy. thanks!

**Comment by voxik** [comment]
```rake test``` should do the job. The test suite is designed for MiniTest

**Comment by voxik** [comment]
@glensc ping ... any update on this?

**Comment by voxik** [comment]
Ups, sorry, closed just by accident.

**Comment by glensc** [comment]
no, haven't worked on this. so it's lost in sea of tickets

**Comment by glensc** [comment]
added test file, but it prints "default" should print i think "pld", seems it needs tests refactoring to be mock other calls? can you just take over from here?

```
➔ rake test test/test_distro.rb
Warning: you should require 'minitest/autorun' instead. 
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/share/ruby/2.1/minitest/autorun.rb:15:in `<top (required)>'
  /home/users/glen/rpm/packages/gem2rpm/gem2rpm/test/helper.rb:6:in `<top (required)>'
  /home/users/glen/rpm/packages/gem2rpm/gem2rpm/test/templates/test_fedora.rb:1:in `require'
  /home/users/glen/rpm/packages/gem2rpm/gem2rpm/test/templates/test_fedora.rb:1:in `<top (required)>'
  /home/users/glen/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
  /home/users/glen/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
  /home/users/glen/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
  /home/users/glen/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit.autorun is now Minitest.autorun. From /usr/share/ruby/2.1/minitest/autorun.rb:19:in `<top (required)>'
Run options: --seed 54001

# Running:

..................S...................................................F

Finished in 6.012640s, 11.8085 runs/s, 25.1138 assertions/s.

  1) Failure:
TestDistro#test_nature_for_os_release_file_pld [/home/users/glen/rpm/packages/gem2rpm/gem2rpm/test/test_distro.rb:58]:
Expected: "pld"
  Actual: "default"

71 runs, 151 assertions, 1 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/users/glen/.gem/ruby/gems/rake-10.5.0/lib" "/home/users/glen/.gem/ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/templates/test_fedora.rb" "test/templates/test_fedora_vagrant_plugin.rb" "test/test_configuration.rb" "test/test_distro.rb" "test/test_gem2rpm.rb" "test/test_helpers.rb" "test/test_specification.rb" "test/test_template.rb" "test/test_template_helpers.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by glensc** [comment]
ah, needed to add `test/templates/fake_files/pld.spec.erb`, now passes

but i still think the test framework should be improved so the template file would be mocked in test as well.

**Comment by glensc** [comment]
uhm. here's some weird github desync issue. my push was success, but i do not see it in github. double checked the urls, just can't see the pushed result here.

```
[~/rpm/packages/gem2rpm/gem2rpm (os-release-quotes)⚡] ➔ git remote -v|grep origin
origin  git@github.com:glensc/gem2rpm.git (fetch)
origin  git@github.com:glensc/gem2rpm.git (push)
[~/rpm/packages/gem2rpm/gem2rpm (os-release-quotes)⚡] ➔ git push origin os-release-quotes
Everything up-to-date
[~/rpm/packages/gem2rpm/gem2rpm (os-release-quotes)⚡] ➔ git log -1
commit 6a57a5e689f8c92531371b6ac4d0571ce4ac199f
Author: Elan Ruusamäe <glen@delfi.ee>
Date:   Mon May 23 19:29:18 2016 +0300

    add fake pld.spec.erb
```

**Comment by voxik** [comment]
Just one minor nit. Would you mind to rename the pld-os-release to quoted-os-release and similarly the test case test_nature_for_os_release_file_pld to test_nature_for_quoted_os_release_file? I'd say that it would be more descriptive why we are actually testing this.

Also it would probably make sense to squash the commits.

Thank you.

**Comment by glensc** [comment]
updated

**Comment by voxik** [comment]
Thank you! Appreciate that.

**Pull request merged**
